### PR TITLE
Development

### PR DESCRIPTION
**Pull request by hugopassos**

### CODE REVIEW

**Review by mosaaleb — CHANGES_REQUESTED** [review]
## Hi @hugopassos, @Juakata :wave:

### Amazing work team :clap:. You have perfectly handled most of the requirments. Still there some minor requirements to be met before moving on.


### Main content
- [ ] All images and videos should be enclosed by a `<figure>` tag with `<figcaption>` that gives a description of the embedded image or video
- [ ] Any sections that include text (paragraphs) should be wrapped with a `<section>` tag and include an `<aside>` tag for Editor's picks and a Sign-Up button.

### Footer
- [ ] It includes a *go to homepage* link on the top right corner of the footer.

Also, I see alot of inline css styles in `index.html`. Let's try not to write inline styling as it is hard to read also it is against best practices.

Please submit a new code review once you finish these requirements.

Happy coding :computer:

**Comment by Torres-ssf** [comment]
### Pull Request Under Review By Sérgio (TSE)

**Comment by Torres-ssf** [comment]
### Awesome work team 👏
You have been worked hard on this project. But still have somethings that we need to change to be in line with Microverse guidelines. The changes are:

- [ ] Microverse guidelines require that your `nav id="nav-footer"` must be part of the footer.

- [ ] All images and videos should be enclosed by a figure tag with figcaption that gives a description of the embedded image or video. This applies to every single image on the page.

- [ ]  There are some errors in your HTML code. Check them using this HTML [validator](https://validator.w3.org/) . Ignore the warnings.

- [ ] It makes sense to include the top navbar inside the header

Please kindly make these changes and submit for code review again.

**Comment by mcrd25** [comment]
# Under review

**Review by mcrd25 — APPROVED** [review]
# Excellent Work! Congratulations 🎉 🚀 🎉 

Hi @hugopassos and @Juakata 👋,

This project is really well done! It looks really really well! 🥇 
You have successfully implemented all changes requested of previous reviewer and I have no complaints!
**You may now move unto the next project! ㊗️**

*One thing I'd suggest is that you implement [GitHub Flow](https://guides.github.com/introduction/flow/) in next HTML/CSS project with an appropriately named feature branch.*

***If you have any questions, now or in the future, do not hesitate to contact me on social media or on slack and I will be glad to chat with you.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/)

**Pull request merged**
